# Generated by Django 4.2.2 on 2023-06-18 12:40

from django.db import migrations, models
import django.utils.timezone
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=recipes.models.recipe_image_file_path),
            preserve_default=False,
        ),
    ]
